// Client-safe helper functions for media URL resolution

import type { MediaImage } from "./types";
import { withBasePath } from "./basePath";

/**
 * Resolve a media URL from a MediaImage object or raw string.
 * Images generated by the build pipeline are served from the Next.js
 * public folder at /images/projects/* — so a plain path is returned as-is.
 */
export function getMediaUrl(
  image: MediaImage | string | null | undefined
): string | null {
  if (!image) return null;

  if (typeof image === "string") {
    return image.startsWith("http") ? image : withBasePath(image);
  }

  return image.url ? withBasePath(image.url) : null;
}
